# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - 'WebApi/**'
      - 'cdk-deploy/**'
    branches:
      - main
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install dependencies for CDK
      working-directory: cdk-deploy
      run: dotnet restore

    - name: Build CDK project
      working-directory: cdk-deploy
      run: dotnet build

    - name: Deploy CDK Stack
      working-directory: cdk-deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: cdk deploy --require-approval never
